#Everything here is shared across prod,dev and QA application files

server:
  port: 8080
  servlet:
    path: /
  error:
    include-stacktrace: never
    include-exception: false
    include-message: never


spring:
  application:
    name: simpilist
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
#        ddl-auto: update #use this for development
        #    ddl-auto: validate # use this for production
  datasource:
    driver-class-name: org.postgresql.Driver



security:
  PBKDF2-iterations: 65536
  PBKDF2-bits: 256
  PBKDF2-algorithm: PBKDF2WithHmacSHA256
  salt-bytes-length: 16
  jwt:
    secret: "This is a test secret will replace later with env variable"
    access-expiration: 900000
    refresh-expiration: 604800000

